---

- name: Wait clickhouse-server port
  wait_for:
    port: 9000
    delay: 10

- name: Create DB
  command: clickhouse-client --query="CREATE DATABASE IF NOT EXISTS {{ clickhouse_db_name }}";


- name: Create replicated migration table
  command: clickhouse-client --query "{{ clickhouse_migration_replicated_table_ddl }}"
  when: clickhouse_migration_create_replicated_table